// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqcqjvhgheknhnwpihpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxY3FqdmhnaGVrbmhud3BpaHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODA5NTcsImV4cCI6MjA2MzY1Njk1N30.P_HShyTf5au_0GuCkEIOU2AxpDzauP8yT1Q4Kqlkxzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);